//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod zostal wygenerowany przez narzedzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku moga spowodowac nieprawidlowe zachowanie i zostana utracone, jesli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reflex_Rehab.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagajaca zdefiniowania typu do wyszukiwania zlokalizowanych ciagow itd.
    /// </summary>
    // Ta klasa zostala automatycznie wygenerowana za pomoca klasy StronglyTypedResourceBuilder
    // przez narzedzie, takie jak ResGen lub Visual Studio.
    // Aby dodac lub usunac skladowa, edytuj plik ResX, a nastepnie ponownie uruchom narzedzie ResGen
    // z opcja /str lub ponownie utworz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystapienie ResourceManager uzywane przez te klase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reflex_Rehab.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przeslania wlasciwosc CurrentUICulture biezacego watku dla wszystkich
        ///   przypadkow przeszukiwania zasobow za pomoca tej klasy zasobow wymagajacej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasob typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_hex_backgrounds_networking {
            get {
                object obj = ResourceManager.GetObject("rsz_hex-backgrounds-networking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
